In [111]:
import pandas as pd
df_ano2024 = pd.read_stata(r"C:\Users\El economista\Documents\GitHub\-BigDataUBA-Grupo-25\TPs\TP 2\EPH_usu_1er_Trim_2024_xlsx\usu_individual_T124.dta")

In [112]:
df_ano2004, meta = pyreadstat.read_sav(r"C:\Users\El economista\Documents\GitHub\-BigDataUBA-Grupo-25\TPs\TP 2\EPH 2004\Individual_t104.sav")

In [113]:
df_ano2004.columns = df_ano2004.columns.str.lower()
df_ano2024.columns = df_ano2024.columns.str.lower()

In [114]:
df_completo = pd.concat([df_ano2004, df_ano2024], ignore_index=True)

In [115]:
df_completo

,codusu,nro_hogar,componente,h15,ano4,trimestre,region,mas_500,aglomerado,pondera,...,adeccfr,pj1_1,pj2_1,pj3_1,idimpp,ch05,imputa,pondiio,pondii,pondih
0,125098,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,1299.0,...,04,0.0,0.0,0.0,00000,NaN,NaN,NaN,NaN,NaN
1,125397,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,2018.0,...,00,0.0,0.0,0.0,00000,NaN,NaN,NaN,NaN,NaN
2,125515,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,1486.0,...,05,0.0,0.0,0.0,00020,NaN,NaN,NaN,NaN,NaN
3,125558,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,1674.0,...,06,0.0,0.0,0.0,00000,NaN,NaN,NaN,NaN,NaN
4,125558,1.0,2.0,1.0,2004.0,1.0,1.0,S,32.0,1674.0,...,06,0.0,0.0,0.0,00000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91334,TQRMNOPUQHKMKNCDEIJAH00861661,1.0,1.0,1.0,2024.0,1.0,1.0,S,33.0,3410.0,...,12.0,NaN,NaN,NaN,NaN,1980-08-18 00:00:00,NaN,4081.0,0.0,0.0
91335,TQRMNOPUQHKMKNCDEIJAH00861661,1.0,2.0,2.0,2024.0,1.0,1.0,S,33.0,3410.0,...,12.0,NaN,NaN,NaN,NaN,2002-03-18 00:00:00,NaN,3410.0,3410.0,0.0
91336,TQRMNOPUQHKMKNCDEIJAH00861661,1.0,3.0,2.0,2024.0,1.0,1.0,S,33.0,3410.0,...,12.0,NaN,NaN,NaN,NaN,2004-01-03 00:00:00,NaN,3410.0,3410.0,0.0
91337,TQRMNOPUQHKMKNCDEIJAH00861661,1.0,4.0,2.0,2024.0,1.0,1.0,S,33.0,3410.0,...,12.0,NaN,NaN,NaN,NaN,2012-05-28 00:00:00,NaN,3410.0,3410.0,0.0
91338,TQRMNOPUQHKMKNCDEIJAH00861661,1.0,5.0,2.0,2024.0,1.0,1.0,S,33.0,3410.0,...,12.0,NaN,NaN,NaN,NaN,1999-04-10 00:00:00,NaN,3410.0,3410.0,0.0