In [14]:
import pyreadstat
# Cargar el archivo .sav
df_ano2004 = pyreadstat.read_sav(R"C:\Users\El economista\Documents\GitHub\-BigDataUBA-Grupo-25\TPs\TP 2\EPH 2004\Individual_t104.sav")

In [17]:
import pandas as pd
# Guardar como archivo .dta
df.to_stata(r"C:\Users\El economista\Documents\GitHub\-BigDataUBA-Grupo-25\TPs\TP 2\EPH 2004\Individual_t104.dta", write_index=False)

In [36]:
df_ano2004 = pd.read_stata(r"C:\Users\El economista\Documents\GitHub\-BigDataUBA-Grupo-25\TPs\TP 2\EPH 2004\Individual_t104.dta")

In [47]:
df_ano2004

,CODUSU,nro_hogar,componente,h15,ano4,trimestre,region,mas_500,aglomerado,pondera,...,deccfr,ideccfr,rdeccfr,gdeccfr,pdeccfr,adeccfr,pj1_1,pj2_1,pj3_1,idimpp
0,125098,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,1299.0,...,07,,06,06,,04,0.0,0.0,0.0,00000
1,125397,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,2018.0,...,00,,00,00,,00,0.0,0.0,0.0,00000
2,125515,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,1486.0,...,07,,07,07,,05,0.0,0.0,0.0,00020
3,125558,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,1674.0,...,08,,08,08,,06,0.0,0.0,0.0,00000
4,125558,1.0,2.0,1.0,2004.0,1.0,1.0,S,32.0,1674.0,...,08,,08,08,,06,0.0,0.0,0.0,00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45284,285733,1.0,1.0,1.0,2004.0,1.0,44.0,N,31.0,123.0,...,09,09,08,,09,07,0.0,0.0,0.0,00000
45285,285733,1.0,2.0,1.0,2004.0,1.0,44.0,N,31.0,123.0,...,09,09,08,,09,07,0.0,0.0,0.0,00000
45286,285733,1.0,3.0,1.0,2004.0,1.0,44.0,N,31.0,123.0,...,09,09,08,,09,07,0.0,0.0,0.0,00000
45287,285733,1.0,4.0,0.0,2004.0,1.0,44.0,N,31.0,123.0,...,09,09,08,,09,07,0.0,0.0,0.0,00000
45288,285733,1.0,5.0,0.0,2004.0,1.0,44.0,N,31.0,123.0,...,09,09,08,,09,07,0.0,0.0,0.0,00000

In [45]:
df_ano2024filt = df_ano2004[df_ano2004["region"] == 1.0]

In [46]:
df_ano2024filt

,CODUSU,nro_hogar,componente,h15,ano4,trimestre,region,mas_500,aglomerado,pondera,...,deccfr,ideccfr,rdeccfr,gdeccfr,pdeccfr,adeccfr,pj1_1,pj2_1,pj3_1,idimpp
0,125098,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,1299.0,...,07,,06,06,,04,0.0,0.0,0.0,00000
1,125397,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,2018.0,...,00,,00,00,,00,0.0,0.0,0.0,00000
2,125515,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,1486.0,...,07,,07,07,,05,0.0,0.0,0.0,00020
3,125558,1.0,1.0,1.0,2004.0,1.0,1.0,S,32.0,1674.0,...,08,,08,08,,06,0.0,0.0,0.0,00000
4,125558,1.0,2.0,1.0,2004.0,1.0,1.0,S,32.0,1674.0,...,08,,08,08,,06,0.0,0.0,0.0,00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7642,288171,1.0,3.0,0.0,2004.0,1.0,1.0,S,33.0,1454.0,...,08,,08,08,,09,0.0,0.0,0.0,00000
7643,288405,1.0,1.0,1.0,2004.0,1.0,1.0,S,33.0,1673.0,...,02,,02,02,,02,0.0,0.0,0.0,00000
7644,288405,1.0,2.0,1.0,2004.0,1.0,1.0,S,33.0,1673.0,...,02,,02,02,,02,0.0,0.0,0.0,00000
7645,288405,1.0,3.0,1.0,2004.0,1.0,1.0,S,33.0,1673.0,...,02,,02,02,,02,0.0,0.0,0.0,00000
7646,288405,1.0,4.0,1.0,2004.0,1.0,1.0,S,33.0,1673.0,...,02,,02,02,,02,0.0,0.0,0.0,00000

In [26]:
df_ano2024 = pd.read_stata(r"C:\Users\El economista\Documents\GitHub\-BigDataUBA-Grupo-25\TPs\TP 2\EPH_usu_1er_Trim_2024_xlsx\usu_individual_T124.dta")

In [27]:
df_ano2024

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,PDECIFR,ADECIFR,IPCF,DECCFR,IDECCFR,RDECCFR,GDECCFR,PDECCFR,ADECCFR,PONDIH
0,TQRMNOPUTHLMKQCDEGGFB00852588,2024.0,1.0,1.0,3.0,1.0,42.0,S,10.0,439.0,...,NaN,12.0,0.0,12.0,12.0,12.0,12.0,NaN,12.0,0.0
1,TQRMNOPUTHLMKQCDEGGFB00852588,2024.0,1.0,1.0,4.0,1.0,42.0,S,10.0,439.0,...,NaN,12.0,0.0,12.0,12.0,12.0,12.0,NaN,12.0,0.0
2,TQRMNOPUTHLMKQCDEGGFB00852588,2024.0,1.0,1.0,5.0,0.0,42.0,S,10.0,439.0,...,NaN,12.0,0.0,12.0,12.0,12.0,12.0,NaN,12.0,0.0
3,TQRMNOPPWHLLKRCDEGGFB00852574,2024.0,1.0,1.0,1.0,1.0,42.0,S,10.0,675.0,...,NaN,8.0,212500.0,6.0,6.0,6.0,6.0,NaN,6.0,1610.0
4,TQRMNOPPWHLLKRCDEGGFB00852574,2024.0,1.0,1.0,2.0,1.0,42.0,S,10.0,675.0,...,NaN,8.0,212500.0,6.0,6.0,6.0,6.0,NaN,6.0,1610.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46045,TQRMNOPUQHKMKNCDEIJAH00861661,2024.0,1.0,1.0,1.0,1.0,1.0,S,33.0,3410.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
46046,TQRMNOPUQHKMKNCDEIJAH00861661,2024.0,1.0,1.0,2.0,2.0,1.0,S,33.0,3410.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
46047,TQRMNOPUQHKMKNCDEIJAH00861661,2024.0,1.0,1.0,3.0,2.0,1.0,S,33.0,3410.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
46048,TQRMNOPUQHKMKNCDEIJAH00861661,2024.0,1.0,1.0,4.0,2.0,1.0,S,33.0,3410.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
46049,TQRMNOPUQHKMKNCDEIJAH00861661,2024.0,1.0,1.0,5.0,2.0,1.0,S,33.0,3410.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0

In [43]:
df_ano2024filt = df_ano2024[ df_ano2024["REGION"] == 1.0]

In [44]:
df_ano2024filt

,CODUSU,ANO4,TRIMESTRE,NRO_HOGAR,COMPONENTE,H15,REGION,MAS_500,AGLOMERADO,PONDERA,...,PDECIFR,ADECIFR,IPCF,DECCFR,IDECCFR,RDECCFR,GDECCFR,PDECCFR,ADECCFR,PONDIH
245,TQRMNOSUWHLKMUCDEIJAH00855260,2024.0,1.0,1.0,1.0,1.0,1.0,S,33.0,1810.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
246,TQRMNOSUWHLKMUCDEIJAH00855260,2024.0,1.0,1.0,2.0,1.0,1.0,S,33.0,1810.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
247,TQRMNOSUWHLKMUCDEIJAH00855260,2024.0,1.0,1.0,3.0,1.0,1.0,S,33.0,1810.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
255,TQSMNORWVHLLKQCDEIJAH00856914,2024.0,1.0,1.0,1.0,1.0,1.0,S,33.0,2368.0,...,NaN,6.0,500000.0,9.0,NaN,9.0,9.0,NaN,9.0,3324.0
256,TQRMNOPQQHLOLRCDEIJAH00855133,2024.0,1.0,1.0,1.0,1.0,1.0,S,33.0,1223.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46045,TQRMNOPUQHKMKNCDEIJAH00861661,2024.0,1.0,1.0,1.0,1.0,1.0,S,33.0,3410.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
46046,TQRMNOPUQHKMKNCDEIJAH00861661,2024.0,1.0,1.0,2.0,2.0,1.0,S,33.0,3410.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
46047,TQRMNOPUQHKMKNCDEIJAH00861661,2024.0,1.0,1.0,3.0,2.0,1.0,S,33.0,3410.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
46048,TQRMNOPUQHKMKNCDEIJAH00861661,2024.0,1.0,1.0,4.0,2.0,1.0,S,33.0,3410.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0
46049,TQRMNOPUQHKMKNCDEIJAH00861661,2024.0,1.0,1.0,5.0,2.0,1.0,S,33.0,3410.0,...,NaN,12.0,0.0,12.0,NaN,12.0,12.0,NaN,12.0,0.0